---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    maxNoOfPodsToEvictPerNamespace: 8
    profiles:
    - name: ToolingNodes
      pluginConfig:
      - name: DefaultEvictor
        args:
          evictFailedBarePods: true
          evictLocalStoragePods: true
          nodeFit: true
          nodeSelector: node-role.kubernetes.io/control-plane!=true
          priorityThreshold:
            value: 3999999
      - name: HighNodeUtilization
        args:
          thresholds:
            cpu: 50
            memory: 50
            pods: 20
      - name: HighNodeUtilizationCordoner
        args:
          thresholds:
            cpu: 50
            memory: 50
            pods: 20
          nodeSelector: node-role.kubernetes.io/control-plane!=true
          minTimeUnderutilized: "5m"
          maxCordonDuration: "10m"
      plugins:
        balance:
          enabled:
          - HighNodeUtilization
          - HighNodeUtilizationCordoner
